name: rive_splash_screen
description: Facilitator for having a Splash screen with a Rive animation until some work has been done for the initialization of the app
version: 0.1.1
homepage: https://github.com/jaumard/rive_splash_screen

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  rive_loading: ">=0.1.3 <1.0.0"
    #path: '../rive_loading'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
